-- Generated by sqrrl. Review before applying; preserve migration history.

CREATE TABLE main."images" (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "title" TEXT NOT NULL,
  "content" BLOB
) STRICT;

CREATE TABLE main."sessions" (
  "token" TEXT NOT NULL,
  "csrf" TEXT NOT NULL,
  "expires" REAL NOT NULL,
  PRIMARY KEY ("token")
) STRICT;
