# Code generated by sqrrl. DO NOT EDIT.
# fmt: off
from sqrrl.postgres import Row
from sqrrl.schema import Schema
from dataclasses import dataclass
from contextlib import asynccontextmanager
from sqrrl.runtime import Increment as _Increment
from builtins import bytes as _bytes, int as _int, float as _float, str as _str
from sqrrl.runtime import decode_blob, decode_integer, decode_real, decode_text, decode_nullable
from typing import AsyncGenerator as _AsyncGenerator, Iterable as _Iterable, Optional, Optional as _Optional
from sqrrl.runtime import UNSET, UNSET as _UNSET, Column as _Column, Conflict as _Conflict, Database, Predicate, Repository, Unset, Unset as _Unset


@dataclass(frozen=True, slots=True, kw_only=True)
class Image:
    id: _int
    title: _str
    content: _Optional[_bytes]


@dataclass(frozen=True, slots=True, kw_only=True)
class ImageCreate:
    id: _int | _Unset = _UNSET
    title: _str
    content: _Optional[_bytes] | _Unset = _UNSET

@dataclass(frozen=True, slots=True, kw_only=True)
class Session:
    token: _str
    csrf: _str
    expires: _float


@dataclass(frozen=True, slots=True, kw_only=True)
class SessionCreate:
    token: _str
    csrf: _str
    expires: _float


_SCHEMA = Schema.from_dict({'tables': ({'fields': ({'is_primary': True, 'kind': 'integer', 'name': 'id'},
                        {'kind': 'text', 'name': 'title'},
                        {'is_nullable': True, 'kind': 'blob', 'name': 'content'}),
             'model': 'Image',
             'name': 'images'},
            {'fields': ({'is_primary': True, 'kind': 'text', 'name': 'token'},
                        {'kind': 'text', 'name': 'csrf'},
                        {'kind': 'real', 'name': 'expires'}),
             'model': 'Session',
             'name': 'sessions'})})


def _decode_images(row: Row) -> Image:
    return Image(
        id=decode_integer(row['id']),
        title=decode_text(row['title']),
        content=decode_nullable(row['content'], decode_blob),
    )


_model_Image = Image


@dataclass(frozen=True)
class _ImageColumns:
    id: _Column[_model_Image, _int] = _Column(_model_Image, _SCHEMA.tables[0].field('id'))
    title: _Column[_model_Image, _str] = _Column(_model_Image, _SCHEMA.tables[0].field('title'))
    content: _Column[_model_Image, _Optional[_bytes]] = _Column(_model_Image, _SCHEMA.tables[0].field('content'))


ImageColumns = _ImageColumns()


class ImageRepository(Repository[Image]):
    def __init__(_self, database: Database) -> None:
        super().__init__(database, _SCHEMA.tables[0], Image, _decode_images)

    async def get(_self, _key: int, /) -> Image:
        return await _self._get((_key,))

    async def create(_self, *, id: int | Unset = UNSET, title: str, content: Optional[bytes] | Unset = UNSET) -> Image:
        return await _self._insert({'id': id, 'title': title, 'content': content})

    async def insert(_self, _row: ImageCreate, /, *, conflict: Optional[_Conflict[Image]] = None) -> Optional[Image]:
        rows = await _self._insert_many(({'id': _row.id, 'title': _row.title, 'content': _row.content},), conflict)
        return rows[0] if rows else None

    async def create_many(_self, _rows: _Iterable[ImageCreate], /, *, conflict: Optional[_Conflict[Image]] = None) -> list[Image]:
        return await _self._insert_many(({'id': _row.id, 'title': _row.title, 'content': _row.content} for _row in _rows), conflict)

    async def update(_self, _key: int, /, *, title: str | Unset = UNSET, content: Optional[bytes] | Unset = UNSET) -> Image:
        return await _self._update((_key,), {'title': title, 'content': content})

    async def update_where(_self, _predicate: Optional[Predicate[Image]] = None, /, *, _all_rows: bool = False, title: str | Unset = UNSET, content: Optional[bytes] | Unset = UNSET) -> int:
        return await _self._update_where(_predicate, {'title': title, 'content': content}, all_rows=_all_rows)

    async def delete(_self, _key: int, /) -> None:
        await _self._delete((_key,))


def _decode_sessions(row: Row) -> Session:
    return Session(
        token=decode_text(row['token']),
        csrf=decode_text(row['csrf']),
        expires=decode_real(row['expires']),
    )


_model_Session = Session


@dataclass(frozen=True)
class _SessionColumns:
    token: _Column[_model_Session, _str] = _Column(_model_Session, _SCHEMA.tables[1].field('token'))
    csrf: _Column[_model_Session, _str] = _Column(_model_Session, _SCHEMA.tables[1].field('csrf'))
    expires: _Column[_model_Session, _float] = _Column(_model_Session, _SCHEMA.tables[1].field('expires'))


SessionColumns = _SessionColumns()


class SessionRepository(Repository[Session]):
    def __init__(_self, database: Database) -> None:
        super().__init__(database, _SCHEMA.tables[1], Session, _decode_sessions)

    async def get(_self, _key: str, /) -> Session:
        return await _self._get((_key,))

    async def create(_self, *, token: str, csrf: str, expires: float) -> Session:
        return await _self._insert({'token': token, 'csrf': csrf, 'expires': expires})

    async def insert(_self, _row: SessionCreate, /, *, conflict: Optional[_Conflict[Session]] = None) -> Optional[Session]:
        rows = await _self._insert_many(({'token': _row.token, 'csrf': _row.csrf, 'expires': _row.expires},), conflict)
        return rows[0] if rows else None

    async def create_many(_self, _rows: _Iterable[SessionCreate], /, *, conflict: Optional[_Conflict[Session]] = None) -> list[Session]:
        return await _self._insert_many(({'token': _row.token, 'csrf': _row.csrf, 'expires': _row.expires} for _row in _rows), conflict)

    async def update(_self, _key: str, /, *, csrf: str | Unset = UNSET, expires: float | _Increment[float] | Unset = UNSET) -> Session:
        return await _self._update((_key,), {'csrf': csrf, 'expires': expires})

    async def update_where(_self, _predicate: Optional[Predicate[Session]] = None, /, *, _all_rows: bool = False, csrf: str | Unset = UNSET, expires: float | _Increment[float] | Unset = UNSET) -> int:
        return await _self._update_where(_predicate, {'csrf': csrf, 'expires': expires}, all_rows=_all_rows)

    async def delete(_self, _key: str, /) -> None:
        await _self._delete((_key,))


class Client:
    def __init__(self, database: Database) -> None:
        self.database = database
        self.images = ImageRepository(database)
        self.sessions = SessionRepository(database)

    @asynccontextmanager
    async def transaction(self) -> _AsyncGenerator[Client]:
        async with self.database.transaction():
            yield Client(self.database)
